# Generated by Django 6.0.3 on 2026-03-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient_provider_staff_remove_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
